### ISSUE TITLE
allowBackup=true necessary?

### ISSUE THREAD

**Issue by edward-s** [gabrielemariotti/changeloglib#20]
Hi,

Nice work on this!

I have a question, is the android:allowBackup = true necessary in your AndroidManifest?

It's causing a manifest merging failed on my own project (which is set to false.. company policy)

**Comment by gabrielemariotti** [comment]
Sorry.
To be removed.

Il giorno gio 18 giu 2015 alle ore 10:45 Edward S <notifications@github.com>
ha scritto:
