### ISSUE TITLE
Library not found

### ISSUE THREAD

**Issue by marbat87** [gabrielemariotti/changeloglib#37]
Hi,

Hi tried to add the dependency to the latest version, but resolver is failing:
![image](https://cloud.githubusercontent.com/assets/8694304/14460878/3c212408-00c0-11e6-9093-84c0cd2b552b.png)

Thanks in advance
Marcello

**Comment by gabrielemariotti** [comment]
It is not updated yet.

**Comment by marbat87** [comment]
@gabrielemariotti  Ok :) When will you do that?

Regards
Marcello

**Comment by gabrielemariotti** [comment]
Now it is public.
