### ISSUE TITLE
Show Dialog 

### ISSUE THREAD

**Issue by GalaxyS5S6S7S8** [gabrielemariotti/changeloglib#42]
How to show up the Dialog??????????!???!!!!!!! My app crashes !

**Comment by gabrielemariotti** [comment]
The ChangeLog Library provides a custom RecyclerView to display a change log.  
The component is a RecyclerView or if your prefer can use a ListView but it is not a Dialog.  

Of course in your dialog you can use it.  
Just check the Android Documentation about it: 
https://developer.android.com/reference/android/support/v4/app/DialogFragment.html. 
In particular way check the show method.

It is not related with with this library.
