### ISSUE TITLE
Feature request: firstRun method

### ISSUE THREAD

**Issue by flubshi** [gabrielemariotti/changeloglib#5]
First: Thanks for your great library!

One feature, developers want to provide using your library, might be to auto show the changelog if a new version is installed. Therefore, it is necessary to determine the installed version and to compare it. In my opinion this is a common use case and should be part of this lib.

My feature suggestion:
Please provide a function e.g. firstRun() which returns true if the app in the current version is started the first time. (other ways to implement this are of course ok, too. e.g. a static constructor autoFirstRun() which shows the changelog only if a new version is installed).

To inspire, you can take a look at the firstRun method of this lib: [See here](http://code.google.com/p/android-change-log/source/browse/trunk/src/sheetrock/panda/changelog/ChangeLog.java)

Thanks!

**Comment by lechuckcaptain** [comment]
Hi Gabriele, sorry to bother you again. Do you need any help or support for the maintenance of the project? I would really appreciate the release of the new version of the library.
